name: Lint Commit Messages & Code

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - name: Lint Commit Messages
      run: npx commitlint-travis
    - name: Lint Code
      run: yarn lint
